{% set name = "pycurl" %}
{% set version = "7.45.4" %}
{% set sha256 = "32c8e237069273f4260b6ae13d1e0f99daae938977016021565dc6e11050e803" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - msvc_warnings.patch                    # [win]
    - pypy-compat.patch                      # [python_impl == 'pypy']

build:
  number: 0
  detect_binary_files_with_prefix: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - libcurl
    - openssl  # [not win]
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - curl
    - pycurl

about:
  home: http://pycurl.sourceforge.net/
  license: LGPL-2.1-or-later OR curl
  license_file:
    - COPYING-LGPL
    - COPYING-MIT
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
  dev_url: https://github.com/pycurl/pycurl

extra:
  recipe-maintainers:
    - tschoonj
    - chrisburr
