{% set name = "pycurl" %}
{% set version = "7.45.1" %}
{% set sha256 = "a863ad18ff478f5545924057887cdae422e1b2746e41674615f687498ea5b88a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - msvc_warnings.patch                     # [win]
    - 0001-Remove-bdist_msi-for-PyPy.patch    # [win and python_impl == 'pypy']

build:
  number: 1
  detect_binary_files_with_prefix: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - libcurl
    - openssl
  run:
    - python

test:
  imports:
    - curl
    - pycurl

about:
  home: http://pycurl.sourceforge.net/
  license: LGPL, MIT
  license_file: COPYING-LGPL
  license_family: LGPL
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
  dev_url: https://github.com/pycurl/pycurl

extra:
  recipe-maintainers:
    - chrisburr
