travis:
  secure:
    BINSTAR_TOKEN: NO+HffGa9F5xKBWqBjPozc864BhhuWKFYuGE/jeQyOyAQcOiK7uKXe735JvOy21q7F1EePDheuBH6nh1jhB3vZPHXzZrACgWJiD/9xJADZX4aCw50vs7ZMhZV3ClIKKwV1dyOvLWZi+AuZwMp8uhgBE407Ng8q1EGxvPCv7G/fVvYBW6x5IP+UbSgrwwtebwfTB5rGoygWq3aLzP0wXGeB2r+TPQkdRYlhrmgKFZOCNmzAzdmsdqSQNXWM0JKlOalbtY7HADpGW/8YXFKAmN3qtPVnkpUi6Rl68otmylWqLP/7JXzAbo/WsEN7zNBOf12nuHLArUd3Pyi89Dsxe9zI15EHycJX6jHYcdh+ymdBfahXg82vOvE5NrmuppJSk/pt6Eab+UAk9uAAjg54BJn43O+lWfoKkWfBsmfR2toQPFzCTFqt7bQCDWG4fpaEolo7WP+WSk8U9DHd6E31DR1IirDaA08rImHL4Eb+PaMMyJHQTqvsYYEJ7XBGVaPnQ3Q2Q4w2WdZuScS+BustbL2N+2Dq5MfUGoBy07dPPhpqfXt3yFDNPDwE1LTIMWe9X0HVBQFj489zg2w4uUZeFIK1zEyHQhBhuQrrZlk+/aFvUlJ5CxSQGTh3lO72H3EM/HG3ZA29OibdUTegreJ9h7uOTtSn4kNBnkGVvqO0ZQeCY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {linux_aarch64: default, linux_ppc64le: default}
